// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: cyd_weather

#ifndef UI_FORECAST_H
#define UI_FORECAST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Forecast
extern void ui_Forecast_screen_init(void);
extern void ui_Forecast_screen_destroy(void);
extern lv_obj_t * ui_Forecast;
extern lv_obj_t * ui_navbar2;
extern void ui_event_btnhome2(lv_event_t * e);
extern lv_obj_t * ui_btnhome2;
extern lv_obj_t * ui_labelhome2;
extern lv_obj_t * ui_btnforecast2;
extern lv_obj_t * ui_labelforecast2;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_labelforecastinfo3;
extern lv_obj_t * ui_forecast3;
extern lv_obj_t * ui_labaldate3;
extern lv_obj_t * ui_labelday3;
extern lv_obj_t * ui_imageiconforcast3;
extern lv_obj_t * ui_labeldaytemp3;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_labelforecastinfo;
// Define ForecastWidget struct at the top
typedef struct {
    lv_obj_t* panel;
    lv_obj_t* date_label;
    lv_obj_t* main_label;
    lv_obj_t* icon_image;
    lv_obj_t* temp_label;
} ForecastWidget;

// Declare the global array
extern ForecastWidget ui_ForecastWidgets[5];
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

