// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: cyd_weather

#include "../ui.h"

lv_obj_t * ui_Forecast = NULL;
lv_obj_t * ui_navbar2 = NULL;
lv_obj_t * ui_btnforecast22 = NULL;
lv_obj_t * ui_labelhome2 = NULL;
lv_obj_t * ui_btnforecast2 = NULL;
lv_obj_t * ui_labelforecast2 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_labelforecastinfo3 = NULL;
lv_obj_t * ui_forecast3 = NULL;
lv_obj_t * ui_labaldate3 = NULL;
lv_obj_t * ui_labelday3 = NULL;
lv_obj_t * ui_imageiconforcast3 = NULL;
lv_obj_t * ui_labeldaytemp3 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_labelforecastinfo = NULL;

// Update your global declarations
ForecastWidget ui_ForecastWidgets[5] = {0};
// event funtions
void ui_event_btnhome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Main_screen_init);
    }
}

// create forecast widgets
static ForecastWidget* create_panels(lv_obj_t *parent, int x, int widget_id) {
    ForecastWidget *widget = &ui_ForecastWidgets[widget_id - 1]; // widget_id is 1-5
    
    // Store the panel
    widget->panel = lv_obj_create(parent);
    lv_obj_set_width(widget->panel, 80);
    lv_obj_set_height(widget->panel, 180);
    lv_obj_set_x(widget->panel, x);
    lv_obj_set_y(widget->panel, 70);
    lv_obj_clear_flag(widget->panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(widget->panel, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(widget->panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(widget->panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(widget->panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(widget->panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(widget->panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(widget->panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create child widgets and store them in the struct
    widget->date_label = lv_label_create(widget->panel);
    lv_obj_set_width(widget->date_label, 70);
    lv_obj_set_height(widget->date_label, 20);
    lv_obj_set_align(widget->date_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(widget->date_label, "---");
    lv_obj_set_style_text_color(widget->date_label, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(widget->date_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(widget->date_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(widget->date_label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    widget->main_label = lv_label_create(widget->panel);
    lv_obj_set_width(widget->main_label, 70);
    lv_obj_set_height(widget->main_label, LV_SIZE_CONTENT);
    lv_obj_set_x(widget->main_label, 0);
    lv_obj_set_y(widget->main_label, 25);
    lv_obj_set_align(widget->main_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(widget->main_label, "---");
    lv_obj_set_style_text_color(widget->main_label, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(widget->main_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(widget->main_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(widget->main_label, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    widget->icon_image = lv_img_create(widget->panel);
    lv_img_set_src(widget->icon_image, &ui_img_icon_01d_72p_png);
    lv_obj_set_width(widget->icon_image, 72);
    lv_obj_set_height(widget->icon_image, 72);
    lv_obj_set_x(widget->icon_image, 0);
    lv_obj_set_y(widget->icon_image, 15);
    lv_obj_set_align(widget->icon_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(widget->icon_image, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(widget->icon_image, LV_OBJ_FLAG_SCROLLABLE);

    widget->temp_label = lv_label_create(widget->panel);
    lv_obj_set_width(widget->temp_label, 70);
    lv_obj_set_height(widget->temp_label, LV_SIZE_CONTENT);
    lv_obj_set_y(widget->temp_label, -5);
    lv_obj_set_align(widget->temp_label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(widget->temp_label, "--/--°C");
    lv_obj_set_style_text_color(widget->temp_label, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(widget->temp_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(widget->temp_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(widget->temp_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    return widget;
}
// build funtions

void ui_Forecast_screen_init(void)
{
    ui_Forecast = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Forecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Forecast, lv_color_hex(0x464653), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Forecast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navbar2 = lv_obj_create(ui_Forecast);
    lv_obj_set_width(ui_navbar2, 320);
    lv_obj_set_height(ui_navbar2, 40);
    lv_obj_set_x(ui_navbar2, 0);
    lv_obj_set_y(ui_navbar2, 320);
    lv_obj_clear_flag(ui_navbar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_navbar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navbar2, lv_color_hex(0x414452), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navbar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navbar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_navbar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navbar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navbar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navbar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_navbar2, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnforecast22 = lv_btn_create(ui_navbar2);
    lv_obj_set_width(ui_btnforecast22, 158);
    lv_obj_set_height(ui_btnforecast22, 40);
    lv_obj_set_align(ui_btnforecast22, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnforecast22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnforecast22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnforecast22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnforecast22, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnforecast22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnforecast22, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnforecast22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnforecast22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnforecast22, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnforecast22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnforecast22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnforecast22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnforecast22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnforecast22, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnforecast22, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_btnforecast22, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_btnforecast22, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_btnforecast22, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_labelhome2 = lv_label_create(ui_btnforecast22);
    lv_obj_set_width(ui_labelhome2, 150);
    lv_obj_set_height(ui_labelhome2, 20);
    lv_obj_set_x(ui_labelhome2, 0);
    lv_obj_set_y(ui_labelhome2, 3);
    lv_label_set_text(ui_labelhome2, "Weather");
    lv_obj_set_style_text_color(ui_labelhome2, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelhome2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelhome2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelhome2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnforecast2 = lv_btn_create(ui_navbar2);
    lv_obj_set_width(ui_btnforecast2, 158);
    lv_obj_set_height(ui_btnforecast2, 40);
    lv_obj_add_state(ui_btnforecast2, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_btnforecast2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_btnforecast2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnforecast2, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnforecast2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_btnforecast2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnforecast2, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnforecast2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnforecast2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnforecast2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnforecast2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnforecast2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnforecast2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnforecast2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnforecast2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnforecast2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnforecast2, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnforecast2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_opa(ui_btnforecast2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_btnforecast2, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnforecast2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_labelforecast2 = lv_label_create(ui_btnforecast2);
    lv_obj_set_width(ui_labelforecast2, 150);
    lv_obj_set_height(ui_labelforecast2, 20);
    lv_obj_set_x(ui_labelforecast2, 0);
    lv_obj_set_y(ui_labelforecast2, 3);
    lv_label_set_text(ui_labelforecast2, "Forecast");
    lv_obj_set_style_text_color(ui_labelforecast2, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelforecast2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelforecast2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelforecast2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Forecast);
    lv_obj_set_width(ui_Panel11, 440);
    lv_obj_set_height(ui_Panel11, 320);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x414452), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Panel11);
    lv_obj_set_width(ui_Panel13, 420);
    lv_obj_set_height(ui_Panel13, 40);
    lv_obj_set_x(ui_Panel13, 10);
    lv_obj_set_y(ui_Panel13, 20);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelforecastinfo3 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_labelforecastinfo3, 400);
    lv_obj_set_height(ui_labelforecastinfo3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelforecastinfo3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelforecastinfo3, "5 DAY FORECAST");
    lv_obj_set_style_text_color(ui_labelforecastinfo3, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelforecastinfo3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelforecastinfo3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelforecastinfo3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelforecastinfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelforecastinfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelforecastinfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelforecastinfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Coordinates from original design
    int x_positions[6] = {10, 95, 180, 265, 350};

    for (int i = 0; i < 5; i++) {
        int x = x_positions[i];

        create_panels(ui_Panel11, x, i + 1);
    }

    ui_Panel14 = lv_obj_create(ui_Panel11);
    lv_obj_set_width(ui_Panel14, 420);
    lv_obj_set_height(ui_Panel14, 26);
    lv_obj_set_x(ui_Panel14, 10);
    lv_obj_set_y(ui_Panel14, 260);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelforecastinfo = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_labelforecastinfo, 400);
    lv_obj_set_height(ui_labelforecastinfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelforecastinfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelforecastinfo, "Last data update: 00:00:00 (Succeed)");
    lv_obj_set_style_text_color(ui_labelforecastinfo, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelforecastinfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelforecastinfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelforecastinfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelforecastinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelforecastinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelforecastinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelforecastinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnforecast22, ui_event_btnhome2, LV_EVENT_ALL, NULL);

}

void ui_Forecast_screen_destroy(void)
{
    if(ui_Forecast) lv_obj_del(ui_Forecast);

    // NULL screen variables
    ui_Forecast = NULL;
    ui_navbar2 = NULL;
    ui_btnforecast22 = NULL;
    ui_labelhome2 = NULL;
    ui_btnforecast2 = NULL;
    ui_labelforecast2 = NULL;
    ui_Panel11 = NULL;
    ui_Panel13 = NULL;
    ui_labelforecastinfo3 = NULL;
    ui_forecast3 = NULL;
    ui_labaldate3 = NULL;
    ui_labelday3 = NULL;
    ui_imageiconforcast3 = NULL;
    ui_labeldaytemp3 = NULL;
    ui_Panel14 = NULL;
    ui_labelforecastinfo = NULL;

    for (int i = 0; i < 5; i++) {
        // The panel will automatically delete all its children when destroyed
        if (ui_ForecastWidgets[i].panel) {
            lv_obj_del(ui_ForecastWidgets[i].panel);
        }
        
        // Reset all pointers to NULL
        ui_ForecastWidgets[i].panel = NULL;
        ui_ForecastWidgets[i].date_label = NULL;
        ui_ForecastWidgets[i].main_label = NULL;
        ui_ForecastWidgets[i].icon_image = NULL;
        ui_ForecastWidgets[i].temp_label = NULL;
    }
}
