// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: cyd_weather

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_mainnavbar = NULL;
lv_obj_t * ui_btnhome = NULL;
lv_obj_t * ui_labelhome = NULL;
lv_obj_t * ui_btnforecast = NULL;
lv_obj_t * ui_labelforecast = NULL;
lv_obj_t * ui_body = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_labelcity = NULL;
lv_obj_t * ui_labeltime = NULL;
lv_obj_t * ui_labelsec = NULL;
lv_obj_t * ui_labelampm = NULL;
lv_obj_t * ui_brightness = NULL;
lv_obj_t * ui_imageiconbrightness = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_labeldate = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_labelweek = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_labelsunrise = NULL;
lv_obj_t * ui_iconsun = NULL;
lv_obj_t * ui_labelsunset = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_labelmoonrise = NULL;
lv_obj_t * ui_iconmoon = NULL;
lv_obj_t * ui_labelmoonset = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_labelinfo = NULL;
lv_obj_t * ui_Panel21 = NULL;
lv_obj_t * ui_imageiconweather = NULL;
lv_obj_t * ui_labelweathermain = NULL;
lv_obj_t * ui_Labelcputext = NULL;
lv_obj_t * ui_Labelcpu = NULL;
lv_obj_t * ui_Labelfpstext = NULL;
lv_obj_t * ui_Labelfps = NULL;
lv_obj_t * ui_imageiconwifi = NULL;
lv_obj_t * ui_Panel22 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_labeltemperature = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_labelfeelslike = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_labeltempmax = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_labeltempmin = NULL;
lv_obj_t * ui_Panel23 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_labelhumidity = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_labelwinddir = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_labelwind = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_labelpressure = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_labelvisibility = NULL;
// event funtions
void ui_event_btnforecast(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Forecast, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Forecast_screen_init);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x414452), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainnavbar = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_mainnavbar, 320);
    lv_obj_set_height(ui_mainnavbar, 40);
    lv_obj_set_x(ui_mainnavbar, 0);
    lv_obj_set_y(ui_mainnavbar, 320);
    lv_obj_clear_flag(ui_mainnavbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mainnavbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainnavbar, lv_color_hex(0x414452), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainnavbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mainnavbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_mainnavbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mainnavbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mainnavbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mainnavbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_mainnavbar, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnhome = lv_btn_create(ui_mainnavbar);
    lv_obj_set_width(ui_btnhome, 159);
    lv_obj_set_height(ui_btnhome, 40);
    lv_obj_set_align(ui_btnhome, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_state(ui_btnhome, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_btnhome, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_btnhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnhome, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_btnhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnhome, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnhome, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnhome, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnhome, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_btnhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_btnhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnhome, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnhome, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_opa(ui_btnhome, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_btnhome, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnhome, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_labelhome = lv_label_create(ui_btnhome);
    lv_obj_set_width(ui_labelhome, 150);
    lv_obj_set_height(ui_labelhome, 20);
    lv_obj_set_x(ui_labelhome, 0);
    lv_obj_set_y(ui_labelhome, 3);
    lv_label_set_text(ui_labelhome, "Weather");
    lv_obj_set_style_text_color(ui_labelhome, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelhome, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelhome, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnforecast = lv_btn_create(ui_mainnavbar);
    lv_obj_set_width(ui_btnforecast, 158);
    lv_obj_set_height(ui_btnforecast, 40);
    lv_obj_add_flag(ui_btnforecast, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnforecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnforecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnforecast, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnforecast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnforecast, lv_color_hex(0x202431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnforecast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnforecast, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnforecast, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnforecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnforecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnforecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnforecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnforecast, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnforecast, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_btnforecast, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_btnforecast, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_btnforecast, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_labelforecast = lv_label_create(ui_btnforecast);
    lv_obj_set_width(ui_labelforecast, 150);
    lv_obj_set_height(ui_labelforecast, 20);
    lv_obj_set_x(ui_labelforecast, 0);
    lv_obj_set_y(ui_labelforecast, 3);
    lv_label_set_text(ui_labelforecast, "Forecast");
    lv_obj_set_style_text_color(ui_labelforecast, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelforecast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelforecast, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelforecast, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_body = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_body, 440);
    lv_obj_set_height(ui_body, 320);
    lv_obj_set_align(ui_body, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_body, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_body, lv_color_hex(0x414452), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_body, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel12, 250);
    lv_obj_set_height(ui_Panel12, 110);
    lv_obj_set_x(ui_Panel12, 10);
    lv_obj_set_y(ui_Panel12, 10);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image5, &ui_img_icon_location_11p_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 10);
    lv_obj_set_y(ui_Image5, 0);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelcity = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_labelcity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelcity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelcity, 30);
    lv_obj_set_y(ui_labelcity, 0);
    lv_label_set_text(ui_labelcity, "Dhaka");
    lv_obj_set_style_text_color(ui_labelcity, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelcity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelcity, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltime = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_labeltime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltime, 5);
    lv_obj_set_y(ui_labeltime, 30);
    lv_label_set_text(ui_labeltime, "00:00");
    lv_obj_set_style_text_color(ui_labeltime, lv_color_hex(0x7CFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltime, &ui_font_DS_Digital_84, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsec = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_labelsec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelsec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsec, 190);
    lv_obj_set_y(ui_labelsec, 54);
    lv_label_set_text(ui_labelsec, "00");
    lv_obj_set_style_text_color(ui_labelsec, lv_color_hex(0x7CFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelsec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelsec, &ui_font_DS_Digital_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelampm = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_labelampm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelampm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelampm, 192);
    lv_obj_set_y(ui_labelampm, 22);
    lv_label_set_text(ui_labelampm, "PM");
    lv_obj_set_style_text_color(ui_labelampm, lv_color_hex(0x7CFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelampm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelampm, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightness = lv_bar_create(ui_Panel12);
    lv_bar_set_value(ui_brightness, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_brightness, 10, LV_ANIM_OFF);
    lv_obj_set_width(ui_brightness, 100);
    lv_obj_set_height(ui_brightness, 5);
    lv_obj_set_x(ui_brightness, -5);
    lv_obj_set_y(ui_brightness, 5);
    lv_obj_set_align(ui_brightness, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_brightness, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_brightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageiconbrightness = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_imageiconbrightness, &ui_img_icon_auto_brightness_16p_png);
    lv_obj_set_width(ui_imageiconbrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageiconbrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imageiconbrightness, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_imageiconbrightness, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageiconbrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel16 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel16, 250);
    lv_obj_set_height(ui_Panel16, 40);
    lv_obj_set_x(ui_Panel16, 10);
    lv_obj_set_y(ui_Panel16, 125);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeldate = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_labeldate, 230);
    lv_obj_set_height(ui_labeldate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labeldate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeldate, "Wed 25-Jan-2026");
    lv_obj_set_style_text_color(ui_labeldate, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeldate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeldate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeldate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel17, 250);
    lv_obj_set_height(ui_Panel17, 25);
    lv_obj_set_x(ui_Panel17, 10);
    lv_obj_set_y(ui_Panel17, 170);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelweek = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_labelweek, 230);
    lv_obj_set_height(ui_labelweek, 20);
    lv_obj_set_align(ui_labelweek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelweek, "WEEK 04");
    lv_obj_set_style_text_color(ui_labelweek, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelweek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelweek, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelweek, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel18, 250);
    lv_obj_set_height(ui_Panel18, 37);
    lv_obj_set_x(ui_Panel18, 10);
    lv_obj_set_y(ui_Panel18, 200);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsunrise = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_labelsunrise, 95);
    lv_obj_set_height(ui_labelsunrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsunrise, 10);
    lv_obj_set_y(ui_labelsunrise, 0);
    lv_obj_set_align(ui_labelsunrise, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelsunrise, "00:00 AM (N)");
    lv_obj_set_style_text_color(ui_labelsunrise, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelsunrise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelsunrise, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelsunrise, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconsun = lv_img_create(ui_Panel18);
    lv_img_set_src(ui_iconsun, &ui_img_icon_sun_32p_png);
    lv_obj_set_width(ui_iconsun, 32);
    lv_obj_set_height(ui_iconsun, 32);
    lv_obj_set_align(ui_iconsun, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconsun, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconsun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelsunset = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_labelsunset, 95);
    lv_obj_set_height(ui_labelsunset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsunset, -10);
    lv_obj_set_y(ui_labelsunset, 0);
    lv_obj_set_align(ui_labelsunset, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_labelsunset, "00:00 PM (N)");
    lv_obj_set_style_text_color(ui_labelsunset, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelsunset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelsunset, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelsunset, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel19, 250);
    lv_obj_set_height(ui_Panel19, 37);
    lv_obj_set_x(ui_Panel19, 10);
    lv_obj_set_y(ui_Panel19, 242);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelmoonrise = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_labelmoonrise, 95);
    lv_obj_set_height(ui_labelmoonrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelmoonrise, 10);
    lv_obj_set_y(ui_labelmoonrise, 0);
    lv_obj_set_align(ui_labelmoonrise, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelmoonrise, "00:00 AM (N)");
    lv_obj_set_style_text_color(ui_labelmoonrise, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelmoonrise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelmoonrise, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelmoonrise, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconmoon = lv_img_create(ui_Panel19);
    lv_img_set_src(ui_iconmoon, &ui_img_icon_new_moon_32p_png);
    lv_obj_set_width(ui_iconmoon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_iconmoon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_iconmoon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconmoon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconmoon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelmoonset = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_labelmoonset, 95);
    lv_obj_set_height(ui_labelmoonset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelmoonset, -10);
    lv_obj_set_y(ui_labelmoonset, 0);
    lv_obj_set_align(ui_labelmoonset, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_labelmoonset, "00:00 PM (N)");
    lv_obj_set_style_text_color(ui_labelmoonset, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelmoonset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelmoonset, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelmoonset, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel20, 250);
    lv_obj_set_height(ui_Panel20, 26);
    lv_obj_set_x(ui_Panel20, 10);
    lv_obj_set_y(ui_Panel20, 285);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelinfo = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_labelinfo, 230);
    lv_obj_set_height(ui_labelinfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelinfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelinfo, "Last data update: 00:00:00 (Succeed)");
    lv_obj_set_style_text_color(ui_labelinfo, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelinfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelinfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelinfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel21, 160);
    lv_obj_set_height(ui_Panel21, 110);
    lv_obj_set_x(ui_Panel21, -10);
    lv_obj_set_y(ui_Panel21, 10);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageiconweather = lv_img_create(ui_Panel21);
    lv_img_set_src(ui_imageiconweather, &ui_img_icon_01d_72p_png);
    lv_obj_set_width(ui_imageiconweather, 72);
    lv_obj_set_height(ui_imageiconweather, 72);
    lv_obj_set_x(ui_imageiconweather, 20);
    lv_obj_set_y(ui_imageiconweather, 5);
    lv_obj_set_align(ui_imageiconweather, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_imageiconweather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageiconweather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelweathermain = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_labelweathermain, 115);
    lv_obj_set_height(ui_labelweathermain, 16);
    lv_obj_set_x(ui_labelweathermain, 3);
    lv_obj_set_y(ui_labelweathermain, 0);
    lv_label_set_long_mode(ui_labelweathermain, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_labelweathermain, "Mainly clear");
    lv_obj_set_style_text_color(ui_labelweathermain, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelweathermain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelweathermain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelweathermain, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelcputext = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_Labelcputext, 40);
    lv_obj_set_height(ui_Labelcputext, 16);
    lv_obj_set_x(ui_Labelcputext, 0);
    lv_obj_set_y(ui_Labelcputext, 30);
    lv_obj_set_align(ui_Labelcputext, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Labelcputext, "CPU");
    lv_obj_set_style_text_color(ui_Labelcputext, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelcputext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelcputext, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelcputext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelcpu = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_Labelcpu, 40);
    lv_obj_set_height(ui_Labelcpu, 16);
    lv_obj_set_x(ui_Labelcpu, 0);
    lv_obj_set_y(ui_Labelcpu, 45);
    lv_obj_set_align(ui_Labelcpu, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Labelcpu, "100%");
    lv_obj_set_style_text_color(ui_Labelcpu, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelcpu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelcpu, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelcpu, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelfpstext = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_Labelfpstext, 30);
    lv_obj_set_height(ui_Labelfpstext, 16);
    lv_obj_set_x(ui_Labelfpstext, 0);
    lv_obj_set_y(ui_Labelfpstext, 70);
    lv_obj_set_align(ui_Labelfpstext, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Labelfpstext, "FPS");
    lv_obj_set_style_text_color(ui_Labelfpstext, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelfpstext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelfpstext, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelfpstext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelfps = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_Labelfps, 30);
    lv_obj_set_height(ui_Labelfps, 16);
    lv_obj_set_x(ui_Labelfps, 0);
    lv_obj_set_y(ui_Labelfps, 85);
    lv_obj_set_align(ui_Labelfps, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Labelfps, "30");
    lv_obj_set_style_text_color(ui_Labelfps, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelfps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelfps, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelfps, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageiconwifi = lv_img_create(ui_Panel21);
    lv_img_set_src(ui_imageiconwifi, &ui_img_icon_wifioff_24p_png);
    lv_obj_set_width(ui_imageiconwifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageiconwifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageiconwifi, -5);
    lv_obj_set_y(ui_imageiconwifi, -2);
    lv_obj_set_align(ui_imageiconwifi, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imageiconwifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_imageiconwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel22 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel22, 160);
    lv_obj_set_height(ui_Panel22, 90);
    lv_obj_set_x(ui_Panel22, -10);
    lv_obj_set_y(ui_Panel22, 125);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_Panel22);
    lv_img_set_src(ui_Image14, &ui_img_icon_temp_22p_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labeltemperature = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_labeltemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltemperature, 20);
    lv_obj_set_y(ui_labeltemperature, -3);
    lv_label_set_text(ui_labeltemperature, "-00.0°C");
    lv_obj_set_style_text_color(ui_labeltemperature, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltemperature, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, 30);
    lv_label_set_text(ui_Label14, "Feels like");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 75);
    lv_obj_set_y(ui_Label1, 30);
    lv_label_set_text(ui_Label1, ":");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelfeelslike = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_labelfeelslike, 67);
    lv_obj_set_height(ui_labelfeelslike, 15);
    lv_obj_set_x(ui_labelfeelslike, 0);
    lv_obj_set_y(ui_labelfeelslike, 30);
    lv_obj_set_align(ui_labelfeelslike, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_labelfeelslike, "-00.0°C");
    lv_obj_set_style_text_color(ui_labelfeelslike, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelfeelslike, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelfeelslike, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelfeelslike, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Panel22);
    lv_img_set_src(ui_Image4, &ui_img_icon_max_11p_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 50);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 15);
    lv_obj_set_y(ui_Label4, 48);
    lv_label_set_text(ui_Label4, "Max");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 75);
    lv_obj_set_y(ui_Label5, 48);
    lv_label_set_text(ui_Label5, ":");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltempmax = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_labeltempmax, 67);
    lv_obj_set_height(ui_labeltempmax, 15);
    lv_obj_set_x(ui_labeltempmax, 0);
    lv_obj_set_y(ui_labeltempmax, 48);
    lv_obj_set_align(ui_labeltempmax, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_labeltempmax, "-00.0°C");
    lv_obj_set_style_text_color(ui_labeltempmax, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltempmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeltempmax, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltempmax, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_Panel22);
    lv_img_set_src(ui_Image12, &ui_img_icon_min_11p_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, 69);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 15);
    lv_obj_set_y(ui_Label6, 66);
    lv_label_set_text(ui_Label6, "Min");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 75);
    lv_obj_set_y(ui_Label7, 66);
    lv_label_set_text(ui_Label7, ":");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltempmin = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_labeltempmin, 67);
    lv_obj_set_height(ui_labeltempmin, 15);
    lv_obj_set_x(ui_labeltempmin, 0);
    lv_obj_set_y(ui_labeltempmin, 66);
    lv_obj_set_align(ui_labeltempmin, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_labeltempmin, "-00.0°C");
    lv_obj_set_style_text_color(ui_labeltempmin, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltempmin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeltempmin, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltempmin, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_body);
    lv_obj_set_width(ui_Panel23, 160);
    lv_obj_set_height(ui_Panel23, 90);
    lv_obj_set_x(ui_Panel23, -10);
    lv_obj_set_y(ui_Panel23, 220);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel23, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel23, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel23, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel23, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_img_create(ui_Panel23);
    lv_img_set_src(ui_Image18, &ui_img_icon_humd_22p_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelhumidity = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_labelhumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelhumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelhumidity, 20);
    lv_obj_set_y(ui_labelhumidity, -3);
    lv_label_set_text(ui_labelhumidity, "000%");
    lv_obj_set_style_text_color(ui_labelhumidity, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelhumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelhumidity, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_Panel23);
    lv_img_set_src(ui_Image13, &ui_img_icon_wind_11p_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, 0);
    lv_obj_set_y(ui_Image13, 30);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelwinddir = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_labelwinddir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelwinddir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelwinddir, 15);
    lv_obj_set_y(ui_labelwinddir, 30);
    lv_label_set_text(ui_labelwinddir, "Wind (NW)");
    lv_obj_set_style_text_color(ui_labelwinddir, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelwinddir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelwinddir, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Panel23);
    lv_obj_set_height(ui_Label23, 15);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label23, 74);
    lv_obj_set_y(ui_Label23, 30);
    lv_label_set_text(ui_Label23, ":");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelwind = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_labelwind, 71);
    lv_obj_set_height(ui_labelwind, 15);
    lv_obj_set_x(ui_labelwind, 0);
    lv_obj_set_y(ui_labelwind, 30);
    lv_obj_set_align(ui_labelwind, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_labelwind, "000.0 km/h");
    lv_obj_set_style_text_color(ui_labelwind, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelwind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelwind, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelwind, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_img_create(ui_Panel23);
    lv_img_set_src(ui_Image15, &ui_img_icon_pressure_11p_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, 0);
    lv_obj_set_y(ui_Image15, 50);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 15);
    lv_obj_set_y(ui_Label8, 48);
    lv_label_set_text(ui_Label8, "Pressure");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 75);
    lv_obj_set_y(ui_Label17, 48);
    lv_label_set_text(ui_Label17, ":");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelpressure = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_labelpressure, 67);
    lv_obj_set_height(ui_labelpressure, 15);
    lv_obj_set_x(ui_labelpressure, 0);
    lv_obj_set_y(ui_labelpressure, 48);
    lv_obj_set_align(ui_labelpressure, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_labelpressure, "0000 hPa");
    lv_obj_set_style_text_color(ui_labelpressure, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelpressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelpressure, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelpressure, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_Panel23);
    lv_img_set_src(ui_Image16, &ui_img_icon_rain_11p_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, 0);
    lv_obj_set_y(ui_Image16, 69);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 15);
    lv_obj_set_y(ui_Label20, 66);
    lv_label_set_text(ui_Label20, "Rain");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 75);
    lv_obj_set_y(ui_Label21, 66);
    lv_label_set_text(ui_Label21, ":");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelvisibility = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_labelvisibility, 67);
    lv_obj_set_height(ui_labelvisibility, 15);
    lv_obj_set_x(ui_labelvisibility, 0);
    lv_obj_set_y(ui_labelvisibility, 66);
    lv_obj_set_align(ui_labelvisibility, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_labelvisibility, "00.0 %");
    lv_obj_set_style_text_color(ui_labelvisibility, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelvisibility, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelvisibility, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelvisibility, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnforecast, ui_event_btnforecast, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brightness, ui_event_brightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imageiconbrightness, ui_event_imageiconbrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imageiconwifi, ui_event_imageiconwifi, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_mainnavbar = NULL;
    ui_btnhome = NULL;
    ui_labelhome = NULL;
    ui_btnforecast = NULL;
    ui_labelforecast = NULL;
    ui_body = NULL;
    ui_Panel12 = NULL;
    ui_Image5 = NULL;
    ui_labelcity = NULL;
    ui_labeltime = NULL;
    ui_labelsec = NULL;
    ui_labelampm = NULL;
    ui_brightness = NULL;
    ui_imageiconbrightness = NULL;
    ui_Panel16 = NULL;
    ui_labeldate = NULL;
    ui_Panel17 = NULL;
    ui_labelweek = NULL;
    ui_Panel18 = NULL;
    ui_labelsunrise = NULL;
    ui_iconsun = NULL;
    ui_labelsunset = NULL;
    ui_Panel19 = NULL;
    ui_labelmoonrise = NULL;
    ui_iconmoon = NULL;
    ui_labelmoonset = NULL;
    ui_Panel20 = NULL;
    ui_labelinfo = NULL;
    ui_Panel21 = NULL;
    ui_imageiconweather = NULL;
    ui_labelweathermain = NULL;
    ui_Labelcputext = NULL;
    ui_Labelcpu = NULL;
    ui_Labelfpstext = NULL;
    ui_Labelfps = NULL;
    ui_imageiconwifi = NULL;
    ui_Panel22 = NULL;
    ui_Image14 = NULL;
    ui_labeltemperature = NULL;
    ui_Label14 = NULL;
    ui_Label1 = NULL;
    ui_labelfeelslike = NULL;
    ui_Image4 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_labeltempmax = NULL;
    ui_Image12 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_labeltempmin = NULL;
    ui_Panel23 = NULL;
    ui_Image18 = NULL;
    ui_labelhumidity = NULL;
    ui_Image13 = NULL;
    ui_labelwinddir = NULL;
    ui_Label23 = NULL;
    ui_labelwind = NULL;
    ui_Image15 = NULL;
    ui_Label8 = NULL;
    ui_Label17 = NULL;
    ui_labelpressure = NULL;
    ui_Image16 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_labelvisibility = NULL;

}
