// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: cyd_weather

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_mainnavbar;
extern lv_obj_t * ui_btnhome;
extern lv_obj_t * ui_labelhome;
extern void ui_event_btnforecast(lv_event_t * e);
extern lv_obj_t * ui_btnforecast;
extern lv_obj_t * ui_labelforecast;
extern lv_obj_t * ui_body;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_labelcity;
extern lv_obj_t * ui_labeltime;
extern lv_obj_t * ui_labelsec;
extern lv_obj_t * ui_labelampm;
extern void ui_event_brightness(lv_event_t * e);
extern lv_obj_t * ui_brightness;
extern void ui_event_imageiconbrightness(lv_event_t * e);
extern lv_obj_t * ui_imageiconbrightness;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_labeldate;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_labelweek;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_labelsunrise;
extern lv_obj_t * ui_iconsun;
extern lv_obj_t * ui_labelsunset;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_labelmoonrise;
extern lv_obj_t * ui_iconmoon;
extern lv_obj_t * ui_labelmoonset;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_labelinfo;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_imageiconweather;
extern lv_obj_t * ui_labelweathermain;
extern lv_obj_t * ui_Labelcputext;
extern lv_obj_t * ui_Labelcpu;
extern lv_obj_t * ui_Labelfpstext;
extern lv_obj_t * ui_Labelfps;
extern void ui_event_imageiconwifi(lv_event_t * e);
extern lv_obj_t * ui_imageiconwifi;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_labeltemperature;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_labelfeelslike;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_labeltempmax;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_labeltempmin;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_labelhumidity;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_labelwinddir;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_labelwind;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_labelpressure;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_labelvisibility;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

