// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: cyd_weather

#include "../ui.h"

lv_obj_t * ui_Provision = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_labelprovisioninfo = NULL;
lv_obj_t * ui_qrcode = NULL;
// event funtions

// build funtions

void ui_Provision_screen_init(void)
{
    ui_Provision = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Provision, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Provision);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, lv_pct(100));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x464653), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qrcode = lv_qrcode_create(ui_Panel2, 200, lv_color_black(), lv_color_white());
    lv_obj_set_y(ui_qrcode, -10);
    lv_obj_set_x(ui_qrcode, lv_pct(0));
    lv_obj_set_align(ui_qrcode, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panel4, 420);
    lv_obj_set_height(ui_Panel4, 26);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -20);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelprovisioninfo = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_labelprovisioninfo, 400);
    lv_obj_set_height(ui_labelprovisioninfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelprovisioninfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelprovisioninfo, "Last data update: 00:00:00 (Succeed)");
    lv_obj_set_style_text_color(ui_labelprovisioninfo, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelprovisioninfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelprovisioninfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelprovisioninfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelprovisioninfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelprovisioninfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelprovisioninfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelprovisioninfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Provision_screen_destroy(void)
{
    if(ui_Provision) lv_obj_del(ui_Provision);

    // NULL screen variables
    ui_Provision = NULL;
    ui_Panel2 = NULL;
    ui_Panel4 = NULL;
    ui_labelprovisioninfo = NULL;
    ui_qrcode = NULL;

}
