// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: cyd_weather

#ifndef UI_PROVISION_H
#define UI_PROVISION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Provision
extern void ui_Provision_screen_init(void);
extern void ui_Provision_screen_destroy(void);
extern lv_obj_t * ui_Provision;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_labelprovisioninfo;
extern lv_obj_t * ui_qrcode;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

