// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: cyd_weather

#ifndef UI_STARTUP_H
#define UI_STARTUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Startup
extern void ui_Startup_screen_init(void);
extern void ui_Startup_screen_destroy(void);
extern lv_obj_t * ui_Startup;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Bar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

