// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: cyd_weather

#include "../ui.h"

static int value = 0;
static lv_timer_t * Slidetimer = NULL;

lv_obj_t * ui_Startup = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Bar = NULL;
// event funtions

// Startup timer
static void set_value_task(lv_timer_t * t) {

    lv_bar_set_range(ui_Bar, 0, 100);
    value++;
    lv_bar_set_value(ui_Bar, value, LV_ANIM_ON); 

    // Limit timer value 100
    if(value >= 100) {
        lv_timer_del(Slidetimer);
        Slidetimer = NULL;
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Main_screen_init);

    }
}

// build funtions

void ui_Startup_screen_init(void)
{
    ui_Startup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Startup);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(100));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x464653), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Startup);
    lv_img_set_src(ui_Image1, &ui_img_logo_png);
    lv_obj_set_width(ui_Image1, 128);
    lv_obj_set_height(ui_Image1, 128);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar = lv_bar_create(ui_Startup);
    lv_obj_set_width(ui_Bar, 200);
    lv_obj_set_height(ui_Bar, 10);
    lv_obj_set_x(ui_Bar, 0);
    lv_obj_set_y(ui_Bar, 90);
    lv_obj_set_align(ui_Bar, LV_ALIGN_CENTER);

    Slidetimer = lv_timer_create(set_value_task, 50, NULL);

}

void ui_Startup_screen_destroy(void)
{
    if(ui_Startup) lv_obj_del(ui_Startup);

    value = 0;
    Slidetimer = NULL;
    // NULL screen variables
    ui_Startup = NULL;
    ui_Panel1 = NULL;
    ui_Image1 = NULL;
    ui_Bar = NULL;

}
