// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: cyd_weather

#ifndef _CYD_WEATHER_UI_H
#define _CYD_WEATHER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Startup.h"
#include "screens/ui_Main.h"
#include "screens/ui_Forecast.h"
#include "screens/ui_Provision.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_icon_location_11p_png);    // assets/icon_location_11p.png
LV_IMG_DECLARE(ui_img_icon_auto_brightness_16p_png);    // assets/icon_auto_brightness_16p.png
LV_IMG_DECLARE(ui_img_icon_sun_32p_png);    // assets/icon_sun_32p.png
LV_IMG_DECLARE(ui_img_icon_new_moon_32p_png);    // assets/icon_new_moon_32p.png
LV_IMG_DECLARE(ui_img_icon_01d_72p_png);    // assets/icon_01d_72p.png
LV_IMG_DECLARE(ui_img_icon_wifioff_24p_png);    // assets/icon_wifioff_24p.png
LV_IMG_DECLARE(ui_img_icon_temp_22p_png);    // assets/icon_temp_22p.png
LV_IMG_DECLARE(ui_img_icon_max_11p_png);    // assets/icon_max_11p.png
LV_IMG_DECLARE(ui_img_icon_min_11p_png);    // assets/icon_min_11p.png
LV_IMG_DECLARE(ui_img_icon_humd_22p_png);    // assets/icon_humd 22p.png
LV_IMG_DECLARE(ui_img_icon_wind_11p_png);    // assets/icon_wind_11p.png
LV_IMG_DECLARE(ui_img_icon_pressure_11p_png);    // assets/icon_pressure_11p.png
LV_IMG_DECLARE(ui_img_icon_rain_11p_png);    // assets/icon_rain_11p.png
LV_IMG_DECLARE(ui_img_icon_01n_72p_png);    // assets/icon_01n_72p.png
LV_IMG_DECLARE(ui_img_icon_02d_72p_png);    // assets/icon_02d_72p.png
LV_IMG_DECLARE(ui_img_icon_02n_72p_png);    // assets/icon_02n_72p.png
LV_IMG_DECLARE(ui_img_icon_03d_03n_72p_png);    // assets/icon_03d_03n_72p.png
LV_IMG_DECLARE(ui_img_icon_04d_04n_72p_png);    // assets/icon_04d_04n_72p.png
LV_IMG_DECLARE(ui_img_icon_09d_09n_72p_png);    // assets/icon_09d_09n_72p.png
LV_IMG_DECLARE(ui_img_icon_10d_72p_png);    // assets/icon_10d_72p.png
LV_IMG_DECLARE(ui_img_icon_10n_72p_png);    // assets/icon_10n_72p.png
LV_IMG_DECLARE(ui_img_icon_11d_11n_72p_png);    // assets/icon_11d_11n_72p.png
LV_IMG_DECLARE(ui_img_icon_13d_13n_72p_png);    // assets/icon_13d_13n_72p.png
LV_IMG_DECLARE(ui_img_icon_50d_50n_72p_png);    // assets/icon_50d_50n_72p.png
LV_IMG_DECLARE(ui_img_icon_first_quarter_32p_png);    // assets/icon_first_quarter_32p.png
LV_IMG_DECLARE(ui_img_icon_full_moon_32p_png);    // assets/icon_full_moon_32p.png
LV_IMG_DECLARE(ui_img_icon_last_quarter_32p_png);    // assets/icon_last_quarter_32p.png
LV_IMG_DECLARE(ui_img_icon_man_brightness_16p_png);    // assets/icon_man_brightness_16p.png
LV_IMG_DECLARE(ui_img_icon_waning_crescent_32p_png);    // assets/icon_waning_crescent_32p.png
LV_IMG_DECLARE(ui_img_icon_waning_gibbous_32p_png);    // assets/icon_waning_gibbous_32p.png
LV_IMG_DECLARE(ui_img_icon_waxing_crescent_32p_png);    // assets/icon_waxing_crescent_32p.png
LV_IMG_DECLARE(ui_img_icon_waxing_gibbous_32p_png);    // assets/icon_waxing_gibbous_32p.png
LV_IMG_DECLARE(ui_img_icon_wifion_24p_png);    // assets/icon_wifion_24p.png

// FONTS
LV_FONT_DECLARE(ui_font_DS_Digital_46);
LV_FONT_DECLARE(ui_font_DS_Digital_84);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
